### ISSUE TITLE
Google and Microsoft services don't work

### ISSUE THREAD

**Issue by carmenfdezb** [leppa/taot#49]
it doesn't work recently, it shows next message: sevice unavailable (Google) and illegal value (Microsoft)

**Comment by leppa** [comment]
Hello and thank you for reporting this.

I just tried Google Translate on my BlackBerry 10 and it seems to work without problems. "Service unavailable" sounds like an issue on the Google server, so I have few questions:

1. What version of TAO Translator do you have?

2. What operating system or phone model do you have?

3. How often does it happen? Does it happen only with some specific text or language combination?

4. Can you post full error message that you get (or screenshot of it)?

As for Microsoft Translator: it seems that my account has run out of its monthly limit. I have a free account and it has a limit of only 2 million chars per month. This limit is for *all* users of TAO Translator *together*.  Unfortunately, raising this limit is [too expensive](https://datamarket.azure.com/dataset/bing/microsofttranslator). Especially considering that I don't earn any money from TAO Translator. You'll have to wait until 25th of November - the limit will be reset on that day.

**Comment by carmenfdezb** [comment]
1. Version 1.2.0
2. SailfishOS in Jolla phone
3. I always use TAO translation to translate text in Spanish (in most case, copy text and paste to translate). It often happens.
4. Here you are a screenshot:

![20151018122709](https://cloud.githubusercontent.com/assets/6286776/10563697/da456ef8-7594-11e5-9353-a045ce41b741.jpg)

As for Microsoft Translator, I always use Google Trasnlation, but I started to use it because Google Translation wasn't work.

Thank you for your attention.

**Comment by leppa** [comment]
Thanks a lot. Apparently, that's a [known issue](https://github.com/soimort/translate-shell/issues/83): Google now tries to block translators that use Google Translate in a free way. Official API is paid, but there is a workaround to use Google Translate for free. Google didn't seem to care previously, but now they started to take measures. I'll see what I can do here.

> As for Microsoft Translator, I always use Google Trasnlation, but I started to use it because Google Translation wasn't work.

Now I see why I might have run out of quota. After Google Translate stopped working more people started using MS Translator.

**Comment by carmenfdezb** [comment]
Ok, thank you for your answer.
