### ISSUE TITLE
Google translator is broken

### ISSUE THREAD

**Issue by kayschubertwebde** [leppa/taot#52]
server replied: Forbidden

**Comment by benaryorg** [comment]
Can confirm: ![screenshot-15-12-19-18-44-38](https://cloud.githubusercontent.com/assets/6145260/11914402/df768d0e-a680-11e5-9c1b-a4b12cb5ef04.png)

**Comment by leppa** [comment]
It's not the first time when Google tries to block free access to their API. And it looks like they did it again. More details about that are in comments to #49.

I'm looking into one workaround currently and if it works, I hope to have a new release by the end of this week.

**Comment by kayschubertwebde** [comment]
Thank you very much. Happy new year.
