### ISSUE TITLE
Google Translate throws an error

### ISSUE THREAD

**Issue by zxcvbnm3230** [leppa/taot#53]
When trying to use Google translate, it throws an error: 'Error downloading https://blah-blah - server replied: Forbidden'

**Comment by Uppis** [comment]
I believe it is the same with Sailfish version. Actually, I couldn't get any of the translators to work, but Google was the only one with clear error message.

**Comment by leppa** [comment]
Hi and sorry for such a delay with my reaction.

Official Google Translate API is paid, but there were workarounds to use Google Translate for free by accessing API used by translate.google.com. Google didn't seem to care previously, but now they started to take measures and block these workarounds. If a new workaround is found, it works for some time but then Google finds a way to block it. This is not the first time it happens: see #36, #49, #52.

At some point, Google might protect their API in a way that you can't make a workaround anymore, so there's no guarantee that Google Translate will continue working in TAO Translator.

Unfortunately, I don't have any time for TAO Translator currently, so don't expect a fix to appear soon even if a workaround exists. Sorry for that.

**Comment by zxcvbnm3230** [comment]
Thank you for the reply.

I see. It is a pity the situation turned like that, but still thank you for all the previous versions. It was a great pleasure to use your soft:)
