### ISSUE TITLE
SSL handshake failing with Google

### ISSUE THREAD

**Issue by stmblfrcr** [leppa/taot#55]
Sorry, to inform you, but there seems to be a problem with Google Translate again.Don't know, if this happened before 1.3.3.1 since I did not check.
![img_20160802_105117](https://cloud.githubusercontent.com/assets/9961488/17322943/71b093e8-588f-11e6-98af-ae50b78f3730.png)

**Comment by leppa** [comment]
Strange. An SSL handshake error fix for Symbian and Nokia N9 (220b9781d89000d122ec2af01bfbafe8abf4d00f) might have broken it.

Do you also get this error with Microsoft Translator or Yandex translation services?

I'll try to take a look this week.

**Comment by leppa** [comment]
I've suspended the 1.3.3 release, so 1.3.2 should be back in the BlackBerry World. You can try downgrading. However, I'd recommend to wait for few hours, because I'm not sure whether suspension is applied immediately.

**Comment by stmblfrcr** [comment]
Thanks. I actually thought myself this could be related to your recent SSL fix . Microsoft and Yandex work fine.

**Comment by leppa** [comment]
Ok, it might be that Google's root CA certificate fails to load for some reason on BlackBerry and causes invalidation of the same CA from the BlackBerry trusted certificates list.

**Comment by stmblfrcr** [comment]
Downgrading works now. Thanks again.

**Comment by donaldraymond** [comment]
This issue has returned. Microsoft translator works fine.
