### ISSUE TITLE
SSL issue with BB10

### ISSUE THREAD

**Issue by stmblfrcr** [leppa/taot#58]
It seems, again there are problems with Google Translate, at least for me. I get a popup saying „SSL Handshake failed: The issuer certificate of a locally looked up certificate could not be found“. Regards.

**Comment by leppa** [comment]
Thanks for reporting the issue. Please, see [#59](https://github.com/leppa/taot/issues/59#issuecomment-374194791) for my reply. I'll close this one as a duplicate.
