### ISSUE TITLE
Yandex.Translate missing lots of languages

### ISSUE THREAD

**Issue by d9h20f** [leppa/taot#60]
On top of that, it only allows for translation between specific languages. For example, Albanian can only be translated to English and Russian.

**Comment by leppa** [comment]
I've never got to implement dynamic fetching of supported languages for translation services, so currently TAOT ships with a static list. As a result, this list gets outdated over time. I'll make sure to update it with the next release.

> it only allows for translation between specific languages

Unlike Google Translate, that supports translating between any languages, Yandex.Translate API provides a defined list of translation pairs and not all combinations of languages are available. I will also update this list of translation pairs with the new release.
